### ISSUE TITLE
RcAsm missed short branches to another page

### ISSUE THREAD

**Issue by mecparts** [dmadole/Elfos-yr#1]
RcAsm wasn't catching a couple of short branches around 'checkbuf' (at 266C and 2670) to 'rcverror' (at 2081). I only noticed it when I was trying to assemble the source with a18. I've created a pull that ought to fix it.

**Comment by dmadole** [comment]
Fixed in https://github.com/dmadole/Elfos-yr/commit/8b6a5905472e4ed3e797c09e82c33c5ac75d3698
